benchmarks/simple-tests/alloc.ml, benchmarks/simple-tests/capi.ml, benchmarks/simple-tests/dune, benchmarks/simple-tests/finalise-dune.inc, benchmarks/simple-tests/finalise.ml, benchmarks/simple-tests/lazy-dune.inc, benchmarks/simple-tests/lazylist.ml, benchmarks/simple-tests/lists-dune.inc, benchmarks/simple-tests/lists.ml, benchmarks/simple-tests/morestacks.ml, benchmarks/simple-tests/ocamlcapi-dune.inc, benchmarks/simple-tests/ocamlcapi.c, benchmarks/simple-tests/ocamlcapi.ml, benchmarks/simple-tests/stacks-dune.inc, benchmarks/simple-tests/stacks.ml, benchmarks/simple-tests/stress-dune.inc, benchmarks/simple-tests/stress.ml, benchmarks/simple-tests/test-capi.ml, benchmarks/simple-tests/weak-dune.inc, benchmarks/simple-tests/weakretain.ml
Added simple tests for:
- ocaml-c api
- lazy
- finalisers
- stacks
- weak arrays
=> More microbenchmarks

benchmarks/mandelbrot/LICENSE, benchmarks/mandelbrot/dune, benchmarks/mandelbrot/mandelbrot_multicore.ml, benchmarks/mandelbrot/mandelbrot_vanilla.ml
One that forks off workers and the other that uses multicore's domains. This will let us compare the two approaches to parallelism.
It's worth pointing out that mandelbrot is an embarrassingly parallel problem with no shared state and where the bulk of the time is spent iterating so the potential gains here from multicore are minimal.
=> Adds two implementations of the Mandelbrot benchmark

Makefile, README.md
The lockfree and kcas packages will only be built when the BENCH_TARGET is multibench.
This fixes the confusing error that KC saw in issue #19.
=> fix for issue #19 (kcas being built even with stock ocaml)

.drone.yml
Basic CI setup that gets all the dependencies setup and does:
`make ocaml-versions/4.07.1.bench`
fails when this returns a non-zero exit (e.g. a benchmark run failing)
=> config to use cloud.drone.io for CI 

Makefile, benchmarks/benchmarksgame/binarytrees5.ml, benchmarks/benchmarksgame/knucleotide.ml, benchmarks/numerical-analysis/fft.ml
This branch:
- removes Gc.set done inline in some tests. 
- fixes up the makefile to handle doing multibench on a given benchmark directory
=> Remove Gc.set from benchmarks

orun/dune, orun/orun.ml
Let orun handle ocaml programs that use escape sequences in stderr (e.g. compilers)
=> Let orun handle ocaml programs that use escape sequences in stderr

orun/orun.ml
fix for typo causing warning in the orun regex for handling escapes.
=> Fix typo in RE string

.drone.yml, Makefile, orun/common.ml, orun/config/detect_os.ml, orun/config/dune, orun/dune, orun/orun.ml, orun/profiler.c, orun/profiler.ml, orun/profiler.mli, orun/reports.ml, orun/reports.mli, orun/wait4.c
This PR adds initial profiling and tracing support to orun.
The intention is to have a separate sandmark iteration on each run that emits profiling, hardware counters and GC instrumentation data for each of the benchmarks to HTML reports or in formats that can easily be analysed. This can enable identifying the cause of a performance regression without having to go through the process of replicating the benchmark environment.
This PR uses the perf_event_open syscall to read profiling events and libdwfl to translate these into file/module/function/line information. It currently relies on LBR in ‘call stack’ mode to capture the call stack though in future it would probably be worth doing DWARF-based unwinding and leverage the branch timing mode of LBR instead.
Interfacing with …
=> Sampling coverage

.drone.yml, Makefile, dependencies/packages/dune/dune.1.7.1/opam, orun/config/detect_os.sh, orun/dune
while things broken with 4.09/trunk and we need to operate over a wide range of compilers 4.06/multicore through trunk.
=> Workaround to use system installed dune for build 

dependencies/repo
Try to get the source archives from https://opam.ocaml.org/cache when we can. Might make things a bit more robust in instances where we are failing to pull the source files.
=> Try to use opam.ocaml.org/cache when we can

benchmarks/stdlib/array.inc, benchmarks/stdlib/array_bench.ml, benchmarks/stdlib/hashtbl.inc, benchmarks/stdlib/map.inc, benchmarks/stdlib/pervasives.inc
move the params to make the runtime a in benchmarks/stdlib more balanced.
=> stdlib rebalance

orun/orun.ml
Hey,
Just as discussed on Slack, this is the hack I used to enable tracing runtime on a sandmark run.
OCAML_EVENTLOG_FILE is just for the output file name, it is not yet kept as a build artifact (because we want to improve size first).
We will just have another compiler branch to test eventlog branch but with tracing off by disabling tracing by default.
=> Add OCAML_EVENTLOG_ENABLED=1 and OCAML_EVENTLOG_FILE

Makefile
that will not collide with other .bench files. 
This proved a problem if you do a run_orun followed by run_perfstat in the same sandmark directory.
=> Merge orun benchmarks into a toplevel .orun.bench file

run_config.json
The name for the lexifi-g2pp test is incorrectly set to 'main'.
=> Fix name for lexifi-g2pp config

benchmarks/multicore-numerical/binarytrees5_multicore.ml, benchmarks/multicore-numerical/game_of_life_multicore.ml, benchmarks/multicore-numerical/matrix_multiplication_multicore.ml, benchmarks/multicore-numerical/matrix_multiplication_tiling_multicore.ml, benchmarks/multicore-numerical/nbody_multicore.ml, benchmarks/multicore-numerical/spectralnorm2_multicore.ml
This PR optimizes the multicore-numerical benchmarks such that the worker threads do not need to block on the response channel.
=> Make response channel for multicore-numerical benchmarks have length 1

Makefile
The PR enforces the use of `--format=columns` with `pip3 list` to handle the following warning: 
```
"DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning."
```
=> Use --format=columns with pip3 list in Makefile

Makefile
Use sudo with specific environment variables to make opam and dune happy to build parallel compiler and benchmarks. Both `run_all_parallel.sh` and `run_all_serial.sh` build fine.
=> Use sudo for parallel benchmark builds

ocaml-versions/4.06.1+multicore+stw+parallel.comp, ocaml-versions/4.06.1+multicore+stw+pausetimes+parallel.comp, ocaml-versions/4.06.1+multicore+stw+pausetimes.comp, ocaml-versions/4.06.1+multicore+stw.comp, ocaml-versions/4.10.0+multicore+parallel.comp, ocaml-versions/4.10.0+multicore+pausetimes+parallel.comp, ocaml-versions/4.10.0+multicore+pausetimes.comp, ocaml-versions/4.10.0+multicore.comp
This PR updates the multicore `ocaml-version/*.comp` files to reflect the new ocaml-multicore naming.
=> Reflect ocaml-multicore repo branch changes

benchmarks/multicore-numerical/binarytrees5_multicore.ml, benchmarks/multicore-numerical/game_of_life_multicore.ml, benchmarks/multicore-numerical/spectralnorm2_multicore.ml
Porting code of Game of Life, Spectralnorm and Binarytree5 from channels to task-api.
Game of Life (n = 256)
|  Domains | Channels | Tasks |
| --- | --- | --- |
|  1 | 45.187 | 44.37 |
|  2 | 23.105 | 22.286 |
|  4 | 11.663 | 11.201 |
|  8 | 5.952 | 5.668 |
|  12 | 4.078 | 3.976 |
|  16 | 3.102 | 2.927 |
|  20 | 2.534 | 2.513 |
|  24 | 2.165 | 2.67 |
Spectralnorm (n = 5500)
|  Domains | Channels | Tasks |
| --- | --- | --- |
|  1 | 7.822 | 8.358 |
|  2 | 3.929 | 4.201 |
|  4 | 1.974 | 2.116 |
|  8 | 1 | 1.071 |
|  12 | 0.683 | 0.732 |
|  16 | 0.526 | 0.562 |
|  20 | 0.431 | 0.476 |
|  24 | 0.369 | 0.393 |
Binarytree5 (n = 23)
|  Domains | Channels | Tasks |
| --- | --- | --- |
|  1 | 69.313 | 71.728 |
|  2 | 42.267 | 41.823 |
|  4 | 24.72 | 23.123 |
|  8 | 13.488 | 12.56 |
|  12 | 12.38 | …
=> Task-api port of Game of Life, Spectralnorm, Binarytree5

.drone.yml, Makefile
1. The PRs #131 and #132 are mutually dependent on each other, and the .drone.yml file was updated to pull the patch from #131 to #132 for the CI. Since, the PRs have been merged, we can now undo the change. 
2. Also, we now use `BUILD_ONLY` in the Makefile and .drone.yml.
=> Use BUILD_ONLY in .drone.yml

.drone.yml, Makefile, micro_multicore.json, multicore_parallel_run_config.json, run_config.json
The current tags are `macro_bench` and `run_in_ci`. The first tag indicates that the benchmark is a macro benchmark. The second tag indicates that the benchmark must be run in the CI. Modify the CI scripts to run the benchmarks tagged as `run_in_ci`. 
The `run_in_ci` tag circumvents #145. Instead of builds only in CI, whose failures are also ignored as some package builds may fail, we only run a subset of the programs in the CI.
=> Add support to associate tags with benchmarks.

.drone.yml
This PR does the following clean ups in .drone.yml:
* Add `python3-pip` as part of the apt-get install step
* Use a single 'apt-get install` command
* Invoke `pip3` to install intervaltree to avoid errors when Makefile is invoked
=> Install python3-pip and intervaltree for clean CI build

benchmarks/multicore-numerical/dune, benchmarks/multicore-numerical/evolutionary_algorithm_multicore.ml, multicore_parallel_run_config.json
This PR adds a parallel benchmark posted in https://github.com/ocaml-multicore/ocaml-multicore/issues/336. 
Its performance numbers for `lambda = 10000, n = 10000`are below: 
Cores | Time(s) | Speedup
-- | -- | --
1 | 93.25 | 1
2 | 50.76 | 1.837076438
4 | 26.42 | 3.529523089
8 | 13.6 | 6.856617647
12 | 8.82 | 10.57256236
16 | 7.31 | 12.75649795
20 | 6.35 | 14.68503937
24 | 5.48 | 17.01642336
=> evolutionary algorithm - parallel benchmark

Makefile, README.md
PR to revert changes in the present in #124 because of the following reasons.
> The PARAMWRAPPER is configured for parallel benchmarks, so while generating run_config_macro.json
> - It overwrites some parameters already configured, making the runs empty. So most of the benchmarks are not being executed in a run.
> - The paramwrapper has the taskset and chrt which is meant for parallel benchmarks and not necessary for sequential benchmarks.
=> revert paramwrapper changes

multicore_parallel_run_config.json
The fix solves the issue of a `Key Error` while running the python notebook in `notebooks/parallel/parallel.ipynb`
The problem was the empty `params` in the serial benchmark of the grammatrix which generated `grammatrix.` as the key instead of `grammatrix.16`
=> fix for key error in the python notebook for grammatrix

benchmarks/multicore-numerical/nbody.ml, benchmarks/multicore-numerical/nbody_multicore.ml
This PR fixes the calculation of the interactions of the bodies and introduce local ref var for velocities to reduce writes and cache traffic.
Given that the inner loop is iterating over all `j  = 0 to Array.length bodies - 1` we should not update the `b'` velocities; updating these velocities is also not parallel domain safe. 
This PR also cuts the false sharing caused by the mutable writes by introducing local reference variables. 
A quick run with `nbody_multicore.exe 16 512 2048` gave:
- no ref vars: ~1.87s
- with ref vars: ~1.32s
=> Fix calculation of nbody_multicore

dependencies/packages/domainslib/domainslib.0.2.1/opam
This PR upgrades domainslib from 0.2.0 to 0.2.1, which will pick up the non-allocating receive poll:
https://github.com/ocaml-multicore/domainslib/releases/tag/0.2.1.
=> upgrade domainslib from 0.2.0 to 0.2.1

dependencies/packages/alt-ergo-lib/alt-ergo-lib.2.3.2/opam, dependencies/packages/alt-ergo-parsers/alt-ergo-parsers.2.3.2/opam, dependencies/packages/alt-ergo/alt-ergo.2.3.2/opam
The `alt-ergo` library and parser fails to build in a sandbox environment. As discussed in https://github.com/OCamlPro/alt-ergo/issues/351, we need to pass the `prefix`, and `libdir` to the `configure` script in order to build the package when using a different _opam directory.
=> Specify prefix,libdir for alt-ergo sandbox builds

Makefile
This is mainly to avoid installing `coq` and `fraplib` when running parallel benchmarking. Building `coq` takes ages, and we don't even use it for the parallel runs. This PR is just a start. Ideally, I'd like to have the `PACKAGES` variable completely and accurately describing the required set of packages for serial and parallel runs so that benchmarking runs can be faster. @shakthimaan @shubhamkumar13.
=> Avoid installing packages which are unused for multicore runs

Makefile
This PR:
* Adds a `check_url` dependency in the Makefile that goes through all the `ocaml-versions/*.json` files to ensure that a URL parameter exists. If not found, it prints the filename.
* On a pristine Ubuntu installation, the `pkg-config` and `m4` packages are required to be installed for Sandmark, and hence the same have been included to `DEPENDENCIES`.
=> Add check_url for .json file and pkg-config,m4 in Makefile

README.md, orun/dune, orun/orun.ml, orun/orun.opam, orun/profiler.ml
The following PR is useful for `flambda` developers who are interested in the codesize (count of CAML symbols) for a benchmark as mentioned in https://github.com/ocaml-bench/sandmark/issues/122.
```
{"name":"knucleotide.", ... ,"codesize":276859.0, ...}
```
Some observed benchmark results (Code Size count):
* alt-ergo     ( 2_822_040  )
* coqc          ( 5_869_305  )
* cpdf           ( 1_131_376  )
* nbody.exe       ( 276_710 )
* stress.exe         ( 84_061 )
* fft.exe               ( 38_914 )
=> Add codesize attribute to .bench in orun

Makefile, README.md, multicore_parallel_run_config.json, run_all_parallel.sh
This PR does a cleanup of using sudo with parallel tests. This caused me some pain recently when running big test instances (which take a long time O(hrs) to run) that failed because files were turning up with root permissions in strange places. 
The changes are:
- remove sudo from the makefile; people should use the capability (or any other alternative) to allow them to run chrt
- make using chrt an explicit wrapper target for `RUN_BENCH_TARGET`. We wanted to be able to benchmark with and without the chrt command.
- be a bit more upfront in the console when the benchmarks run and the parameters being used (this is helpful for things that run for a long time, just in case the user has made a mistake)
- document a method to set permissions for chrt on Linux and other changes to be in line …
=> Cleanup our use of sudo for chrt

orun/dune, orun/orun.ml, orun/orun.opam
The `orun` dependency for `Base` and `Stdio` is removed using this PR to facilitate building Sandmark with trunk.
=> Remove Base, Stdio orun dependency for trunk

benchmarks/multicore-effects/algorithmic_differentiation.ml, benchmarks/multicore-effects/dune, benchmarks/multicore-effects/eratosthenes.ml, benchmarks/multicore-effects/ms_sched.ml, benchmarks/multicore-effects/queens.ml, benchmarks/multicore-effects/test_sched.ml, multicore_effects_run_config.json, run_all_effects.sh
This PR cleans up the existing multicore effect benchmarks that we have in sandmark. 
It gets the existing code compiling cleanly (without warnings), adds a `multicore_effects_run_config.json` config for the existing effect benchmarks, adds a `run_all_effect.sh` script to run things.
=> Clean up existing effect benchmarks

benchmarks/multicore-effects/dune, benchmarks/multicore-effects/effect_throughput_clone.ml, benchmarks/multicore-effects/effect_throughput_perform.ml, benchmarks/multicore-effects/effect_throughput_perform_drop.ml, benchmarks/multicore-effects/effect_throughput_val.ml, multicore_effects_run_config.json
This PR introduces very simple micro benchmarks that are looking at the throughput of our effects system.
In particular it has 4 tests:
- `effect_throughput_clone`: this captures a continuation and then does `continue (Obj.clone_continuation k) x` on it. 
- `effect_throughput_val`: this executes a function inside an effect handler, but returns without performing an effect. 
- `effect_throughput_perform`: this executes a function inside an effect handler, performs an effect, which resumes the continuation which exits with a value.
- `effect_throughput_perform_drop`: this executes a function inside an effect handler, performs an effect, which drops the continuation and so the exit is from the effect handler itself.
These tests are not exhaustive, but are intended to give code coverage to …
=> Very simple effect microbenchmarks to cover code paths

benchmarks/multicore-effects/dune, benchmarks/multicore-effects/rec_eff_ack.ml, benchmarks/multicore-effects/rec_eff_evenodd.ml, benchmarks/multicore-effects/rec_eff_fib.ml, benchmarks/multicore-effects/rec_eff_motzkin.ml, benchmarks/multicore-effects/rec_eff_sudan.ml, benchmarks/multicore-effects/rec_eff_tak.ml, benchmarks/multicore-effects/rec_seq_ack.ml, benchmarks/multicore-effects/rec_seq_evenodd.ml, benchmarks/multicore-effects/rec_seq_fib.ml, benchmarks/multicore-effects/rec_seq_motzkin.ml, benchmarks/multicore-effects/rec_seq_sudan.ml, benchmarks/multicore-effects/rec_seq_tak.ml, multicore_effects_run_config.json
This PR implements a collection of 'recursion' benchmarks for looking at the overheads of effects and inspired by the Manticore benchmarks:
https://github.com/ManticoreProject/benchmark/
The aim it to display the overhead of using effects to spawn stacks for recursive functions over a standard recursive function. It also provides more benchmarks for tuning our effects performance in multicore. 
I had to make some (possibly arbitrary) naming choices:
- I have added all these to `benchmarks/multicore-effects` to keep the code in one place at the cost of things starting to get crowded
- I have tagged these as `recursive` in the run_config json file so there is a tag people can use to filter
- I used the convention `rec_{seq,eff}_{benchmark}.ml` to name these `rec` for `recursive` and …
=> Implementation of 'recursion' benchmarks for effects

Makefile
The following PR implements `Option A` as mentioned in https://github.com/ocaml-bench/sandmark/issues/184. An (optional) `environment` parameter can specified for a wrapper entry in `run_config*.json` as shown below:
```
{
"name": "orun_2M",
"environment": "OCAMLRUNPARAM='s=2M'",
"command": "orun -o %{output} -- taskset --cpu-list 5 %{command}"
},
```
* You can simply add multiple `variable=values` entries to the `environment` parameter value, and it will be passed during run-time execution.
* The `subst` in the Makefile to extract the wrapper name has been replaced by `patsubst` to allow bench target names with underscore like `run_orun_2M`.
You can run the above using:
```
$ RUN_BENCH_TARGET=run_orun_2M make ocaml-versions/4.10.0+multicore.bench
```
=> Add environment support for wrapper in JSON configuration file

.drone.yml, .gitignore, Makefile, README.md, run_all_parallel.sh, run_all_serial.sh, run_config.json
Remove the custom targets `_macro.json` and `_ci.json` and replace that with a generic solution. See #195.
=> Filter benchmarks based on tag

benchmarks/multicore-gcroots/dune, benchmarks/multicore-gcroots/globroots/dune, benchmarks/multicore-gcroots/globroots/globroots.ml, benchmarks/multicore-gcroots/globroots/globrootsprim.c, benchmarks/multicore-gcroots/globroots_mp.ml, benchmarks/multicore-gcroots/globroots_seq.ml, benchmarks/multicore-gcroots/globroots_sp.ml, micro_multicore.json
This patch adds a microbenchmark that measures the efficiency of global root scanning. There are three parts:
1. `globroots_seq.ml` - Single core version adapted from [trunk's testsuite](https://github.com/ocaml/ocaml/blob/trunk/testsuite/tests/gc-roots/globroots.ml).
2. `globroots_sp.ml` - Multicore version of (1), where one domain does all the work and other domains are idle waiting on a channel.
3. `globroots_mp.ml` - Modification of (2), work is split equally among the available domains.
=> global roots microbenchmark

benchmarks/multicore-gcroots/globroots/globroots.ml, benchmarks/multicore-gcroots/globroots_mp.ml, benchmarks/multicore-gcroots/globroots_seq.ml, benchmarks/multicore-gcroots/globroots_sp.ml
Similar to https://github.com/ocaml-multicore/ocaml-multicore/pull/481
=> don't share array in global roots parallel benchmarks

run_config.json
The arguments to `simple-tests/capi` were not being parsed correctly as mentioned in https://github.com/ocaml-bench/sandmark/issues/206, and this PR fixes the same. You can verify using the following commands:
```
$ TAG='"lt_1s"' make run_config_filtered.json
$ RUN_CONFIG_JSON=run_config_filtered.json make ocaml-versions/4.10.0+multicore.bench
```
=> Fix params for simple-tests/capi

Makefile
Add a `benchclean` target to remove the generated benchmarks and the benchmark results.
=> Added bench clean target in the Makefile

Makefile
The following patch implements ITER support when building and executing benchmarks. When used with ITER=2 for 4.10.0+multicore (for example), it correctly creates two separate directories for the benchmarks:
```
sandmark $ ls _build/
4.10.0+multicore_1  4.10.0+multicore_2  log
```
The final consolidated .bench file now uses the ITER value:
```
$ ls _results/
4.10.0+multicore_1.orun.summary.bench  4.10.0+multicore_2.orun.summary.bench
```
You can test the patch using:
```
$ TAG='"run_in_ci"' make run_config_filtered.json
$ ITER=2 RUN_CONFIG_JSON=run_config_filtered.json make ocaml-versions/4.10.0+multicore.bench 
```
=> Implement ITER support

benchmarks/multicore-structures/treiber_stack.ml
4.12+domains removes Gc.promote_to from the runtime ([multicore#489](https://github.com/ocaml-multicore/ocaml-multicore/pull/489)). 
Treiber stack was using the function mentioned above and it might break multicore-structures benchmark when sandmark moves to 4.12+domains and 4.12+domains+effects.
I've tested with domains+effects branch it seems to work without any issue.
I need to check the performance numbers of the benchmarks in multicore-strcutures which use `treiber_stack.ml` and see if there are any difference with this change.
=> Remove Gc.promote_to from treiber_stack.ml

benchmarks/decompress/dune, benchmarks/decompress/test_decompress.ml, benchmarks/decompress/test_decompress_multicore.ml
This PR fixes errors between the amount of work configured and the amount of work done. 
The changes are:
- fix up for indices and explicitly count the amount of work done with an assert that the work done is the work requested. (consider `iterations=4` & `num_domains=2`, in this configuration I make there being _3_ units of work being done by each of the domains and not 2 in the existing code).
- moves the multicore test to use a pool with `parallel_for`; this is important as there are unintended consequences in the existing code (consider `iterations=3` & `num_domains=4`, it will distribute `work 0` to the first three spawned domains and then do 3 units of work in the final domain).
- simplifies the `data_to_compress` setup to use `String.init` which is more idiomatic.
=> Fix up decompress iterations of work

benchmarks/multicore-numerical/floyd_warshall.ml, benchmarks/multicore-numerical/floyd_warshall_multicore.ml
This PR attempts to improve the floyd warshall benchmark. 
It does this by:
- being a bit clearer about the meaning of the edges (`Infinity | Value of int` vs `None | Some of int`)
- fixing the random seed so that runs are repeatable
- avoiding polymorphic compare and making the branches a bit easier to inspect via pattern matching (which also avoids needing a `sum` function)
Over all this improves the performance of the benchmark (untuned Zen2 machine):
=> A better floyd warshall

benchmarks/multicore-numerical/matrix_multiplication.ml, benchmarks/multicore-numerical/matrix_multiplication_multicore.ml
This PR makes small improvements to the efficiency and scaling of our multicore matrix multiplication benchmark. 
The changes are:
- bring `matrix_multiplication` and `matrix_multiplication_multicore` more into line with each other to make things a bit easier to maintain
- avoid writing the results matrix until we have summed the values for the element; this technique was effective with nbody and it is effective here. 
Rough and ready benchmark results on a Zen2 machine (detuned):
=> Some improvements for matrix multiplication

benchmarks/multicore-numerical/nbody_multicore.ml
This PR improves `nbody_multicore` with large core counts, by also parallelising the `energy` function with `parallel_for_reduce`.
Benchmark results with higher core counts and bigger instances:
=> Improve `nbody_multicore` benchmark with high core counts

benchmarks/multicore-numerical/game_of_life.ml, benchmarks/multicore-numerical/game_of_life_multicore.ml
This PR improves the game_of_life benchmarks by:
- inlining hot functions
- avoid initialising the temporary matrix with random numbers
Zen2 (detuned) parallel benchmark numbers:
=> Improve game_of_life benchmark

run_config.json
Remove the `macro_bench` tag from graph500 benchmarks as they are outliers skewing benchmark results and need to be re-implemented.
=> Remove macro_bench from graph500

multicore_parallel_navajo_run_config.json, multicore_parallel_run_config.json
The PR adds `chrt` to the `pausetimes_multicore` wrapper to make sure the taskset argument mentioned in the parawrapper is picked up.
The absence of `chrt` led to the benchmarks not pick up the taskset arguments resulting in slow nightly runs.
Thanks to @Engil he was able to pinpoint the problem to the cores not being used.
=> add chrt to pausetimes_multicore wrapper

benchmarks/multicore-minilight/parallel/rayTracer.ml, benchmarks/multicore-minilight/parallel/scene.ml, benchmarks/multicore-minilight/parallel/spatialIndex.ml, benchmarks/multicore-minilight/parallel/triangle.ml, benchmarks/multicore-numerical/binarytrees5_multicore.ml, benchmarks/multicore-numerical/evolutionary_algorithm_multicore.ml, benchmarks/multicore-numerical/floyd_warshall_multicore.ml, benchmarks/multicore-numerical/mandelbrot6_multicore.ml, benchmarks/multicore-numerical/matrix_multiplication_tiling_multicore.ml, benchmarks/multicore-numerical/nbody_multicore.ml, benchmarks/multicore-numerical/quicksort_multicore.ml
Multicore OCaml programs no longer need Domain.Sync.poll () since safe points have been merged into Multicore OCaml: https://github.com/ocaml-multicore/ocaml-multicore/pull/573. The PR removes the calls to `poll` from the parallel benchmarks in Sandmark.
=> Remove Domain.Sync.poll() from parallel benchmarks 

Makefile
It is unclear whether sandboxing helps in sandmark as sandmark uses a
local opam repo distinct from the global one. Moreover, disabling
sandboxing fixes Docker builds and help with nightly runs on navajo.
=> Disable sandboxing.

.drone.yml, Makefile, benchmarks/decompress/test_decompress_multicore.ml, benchmarks/multicore-minilight/parallel/camera.ml, benchmarks/multicore-minilight/parallel/minilight_multicore.ml, benchmarks/multicore-numerical/LU_decomposition_multicore.ml, benchmarks/multicore-numerical/binarytrees5_multicore.ml, benchmarks/multicore-numerical/evolutionary_algorithm_multicore.ml, benchmarks/multicore-numerical/floyd_warshall_multicore.ml, benchmarks/multicore-numerical/game_of_life_multicore.ml, benchmarks/multicore-numerical/mandelbrot6_multicore.ml, benchmarks/multicore-numerical/matrix_multiplication_multicore.ml, benchmarks/multicore-numerical/mergesort_multicore.ml, benchmarks/multicore-numerical/nbody_multicore.ml, benchmarks/multicore-numerical/quicksort_multicore.ml, benchmarks/multicore-numerical/spectralnorm2_multicore.ml, benchmarks/multicore-structures/test_spsc_queue_pingpong_parallel.ml, dependencies/packages/domainslib/domainslib.0.3.2/opam, ocaml-versions/4.14.0+trunk.json, ocaml-versions/5.00.0+trunk.json, run_config.json
This PR is the first step in adding ocaml 5.0 support for the benchmarks in sandmark.
The PR adds domainslib.0.3.2 and updates the benchmarks supporting the updated api for domainslib
=> Update benchmarks and domainslib to support ocaml 4.14.0+domains (ocaml 5.0)

.drone.yml, ocaml-versions/5.00.0+trunk.json
Adding `5.00+trunk` with the Drone CI `failure:ignore` option so that we will know if trunk fails to build for a PR, but it should not prevent a PR in getting merged if `5.00+stable` builds fine.
=> Re-add 5.00.0+trunk with CI failure:ignore option

ocaml-versions/5.00.0+stable.json, run_all_parallel.sh, run_all_serial.sh
* Updated run_all scripts to use SYS_DUNE_HACK and 5.00.0+stable variant.
* Changed 5.00.0+stable to February 3, 2022 `ocaml/ocaml` commit.
=> Updated run_all scripts and 5.00.0+stable to February 3, 2022 commit

Makefile, ocaml-versions/custom.json, run_all_custom.sh
The PR is for the Custom Variant Support feature request at https://github.com/ocaml-bench/sandmark/issues/274.
* The following parameters (`url`, `tag`, `config_json`, `name`, `expiry`, `environment`, `configure`, `runparams`) are used in an `ocaml-versions/custom.json` file.
* `SANDMARK_NIGHTLY_DIR` can be passed as an environment variable to the `run_all_custom.sh` script.
* The following three URLs are supported:
1. `ocaml/ocaml`
https://github.com/ocaml/ocaml/archive/trunk.tar.gz
2. A specific commit
https://github.com/ocaml/ocaml/archive/b73cbbea4bc40ffd26a459d594a39b99cec4273d.zip
3. A developer branch
https://github.com/sadiqj/ocaml/archive/refs/heads/eventring-pr.zip
* You can test the same using:
```
$ bash run_all_custom.sh
```
=> Add Custom Variant Support feature

Makefile, ocaml-versions/custom.json, run_all_custom.sh
* The `name` in `custom.json` is now used in the `orun.summary.bench` file for use with sandmark-nightly.
* Updated `custom.json` to build for 5.00.0+trunk and 5.00+0+stable targets for both sequential and parallel benchmarks.
* A developer branch is added to demonstrate its use as an example.
=> Use specific name in .orun.summary.bench output

Makefile, ocaml-versions/custom_navajo.json, ocaml-versions/custom_turing.json, run_all_custom.sh
* Use separate custom variant JSON files to build on server machines by using a `CUSTOM_FILE` environment variable.
* The `check_url` is temporarily disabled, and a follow-up issue to update the same has been added at https://github.com/ocaml-bench/sandmark/issues/286.
=> Use separate custom variant JSON files per server

run_all_custom.sh, run_config.json
* Use `--cpu-list` 5 for consistency.
=> Use CPU 5 in run_config.json for consistency

run_all_custom.sh
* Store the log of the build and execution of the benchmark results in the target ${RESULTS_DIR} for the Custom Variant run.
* The co-location of the log and the .bench results are useful for quick reference.
=> Custom script log output to results directory

run_all_custom.sh
Using the `CUSTOM_FILE` environment variable, a raw GitHub JSON file can be provided for the Custom Support Variant feature https://github.com/ocaml-bench/sandmark/issues/274.
=> Allow raw GitHub JSON configuration input for custom variant

Makefile
The OCaml dependencies get overwritten during a build and execution, and need to be cleaned correctly.
=> Clean OCaml dependencies/packages fully after a build

benchmarks/multicore-numerical/LU_decomposition_multicore.ml, benchmarks/multicore-numerical/binarytrees5_multicore.ml, benchmarks/multicore-numerical/nbody_multicore.ml, benchmarks/multicore-numerical/spectralnorm2_multicore.ml
Running `Task.pool` inside the iter function was blocking indefinitely, fixes #294.
=> Use a single `Task.run` in parallel benchmarks

run_all_custom.sh
The `SANDMARK_OVERRIDE_PACKAGES` and `SANDMARK_REMOVE_PACKAGES` can now be specified in the `custom.json` file for the Custom Support Variant. The same has been tested in a sample custom.json file with the following entries:
```
{
"url": "https://github.com/ocaml/ocaml/archive/b73cbbea4bc40ffd26a459d594a39b99cec4273d.zip",
"tag": "run_in_ci",
"config_json": "run_config_filtered.json",
"override_packages": "fmt.0.9.0 ocamlfind.1.9.3 checkseum.0.3.0",
"remove_packages": "camlpdf cpdf coq coq-core coq-stdlib ctypes fraplib index integers irmin irmin-layers irmin-pack js_of_ocaml-compiler ppx_derivers ppx_deriving ppx_deriving_yojson ppx_irmin ppx_repr stdio",
"name": "5.00+trunk+sequential",
"expiry": "2100-01-01"
}
```
This should complete https://github.com/ocaml-bench/sandmark/issues/274.
=> Added dynamic package override and removal for Custom Support Variant

Makefile
The PR has the following changes:
1. A `check_jq` target has been added to ensure that `ocaml-versions/*.json` can be parsed by jq without any errors.
2. The `check_url` has been updated to verify if the `url` field exists for every `ocaml-versions/*.json`, and also will check if the URL actually has a downloadable file using wget.
=> Update check_url and added check_jq

Makefile, nightly_navajo.sh, nightly_turing.sh
This PR moves sandmark-nightly scripts to Sandmark. We need to deploy the nightly script along with the latest run_all_custom.sh script on the benchmarking machine.
=> Move nightly scripts to Sandmark

Makefile
Remove `eventlog-tools` from the Makefile. We will eventually move to using `eventring` for tracing.
=> Remove eventlog-tools

benchmarks/multicore-numerical/dune, benchmarks/multicore-numerical/nqueens_multicore.ml, run_config_byte.json
Adds a toplevel run to fix nqueens failure [encountered on sandmark nightly](https://github.com/ocaml-bench/sandmark-nightly/blob/main/parallel/navajo/20220418_004352/949e2626c22b5fe8159cb29d47207d5621eabf90/5.00%2Btrunk%2Bparallel.20220418_004352.949e2626c22b5fe8159cb29d47207d5621eabf90.log).
Also adds nqueens to bytebench config.
=> Fix nqueens failure

.drone.yml, .github/workflows/main.yml, Makefile, ocaml-versions/5.0.0+stable.json, ocaml-versions/5.0.0+trunk.json
* Use `dune.2.9.3 `from -alpha repository due to restructure of LIBDIR from https://github.com/ocaml/ocaml/pull/11198
* Update `.drone.yml` and GitHub Actions `main.yml` to pin and use dune.2.9.3
* Add `ocamlfind.1.9.3.git` from -alpha repository to build trunk from May 30, 2022.
* Update -stable to May 30, 2022 SHA1 commit.
=> Use -alpha dune.2.9.3 to build with May 30, 2022 trunk

run_all_custom.sh
Closes ocaml-bench/sandmark-nightly-config#6
This check may be too aggressive, i.e., manually running the `run_all_custom.sh` script wouldn't work if a nightly build for that commit already exists, and similarly manual test builds would cause the nightly to skip builds, etc. @shakthimaan let me know if this seems too aggressive to you and if we should skip builds for old commits differently.
=> Skip running build if benchmarks exist for a given commit

run_all_custom.sh
9dbe92fb09602c628dcfbf278b5426a526fb1fef incorrectly used the output of the
command checking if a bench file existed, instead of the exit code of the
command.  This commit fixes that.
=> Fix incorrect check for whether a commit is old

run_config.json
This resolves #348 in the simple way: removing the macro_bench tag from the benches mentionned in the issue.
=> Remove macro_bench tag on select benches

Makefile
Use `git+https` for adding opam remote repository because:
1. The "null update" is much faster when compared to https, as it is a git pull followed by a SHA comparison.
2. In opam 3.x, the HTTP remote will be removed.
=> Use git+https for opam remote repository

bench.Dockerfile
This PR allows the `make bench` command to run sequential benchmarks and record the results in a way that will be consumed by current-bench.
The last thing needed is to enroll the ocaml-bench organisation into the [github app ocaml-benchmarks](https://github.com/marketplace/ocaml-benchmarksv) if that wasn't done already, and to activate it on the sandmark repository.
=> Using sandmark inside current-bench

benchmarks/graph500par/dune, benchmarks/graph500seq/dune, multicore_parallel_navajo_run_config.json, multicore_parallel_run_config.json, run_config.json
Currently the benchmarks `graph500par/kernel1_run` and `graph500seq/kernel1_run` fail because they depend on a file `edges.data` which should be generated first. This is an attempt to fix it by generating `edges.data` using dune rules.
=> Fix execution of Graph500 benchmarks

run_all_custom.sh
This would allow failures when a `/tmp/custom.json` already exists and the sandmark user doesn't have write permissions to the file.
=> Use a different custom file on reach run

benchmarks/chameneos/chameneos_redux_lwt.ml, benchmarks/lexifi-g2pp/optimization.ml, benchmarks/multicore-lockfree/wsqueue-dune.inc, benchmarks/numerical-analysis/dune, benchmarks/sauvola/dune, benchmarks/valet/test_lib.ml, benchmarks/valet/test_lwt.ml
Close https://github.com/ocaml-bench/sandmark/issues/398
Confirmed there are no warnings left when building sequential benchmarks on Navajo with 5.1.0+trunk
=> Fix warnings on sequential build bench

dependencies/template/dev-5.1.0+trunk.opam, dependencies/template/dev.opam
topkg is already a transitive dependency and a new release of topkg and updates to it's dependencies caused the build to fail. This commit drops the explicit dependency on topkg and lets opam install it based on the other dependencies.
=> Remove explicit dependency on a topkg version

Makefile
Adding and removing directories from this list is easier and much more stable than writing sed rules.  It also moves all the benchmark filtering to a single place and makes it easy to see which benchmarks are being ignored.
We use dune's `data_only_dirs` stanza to tell dune to ignore dune files in some directories. This stanza rule only allows specifying immediate sub-directories. So, we create a `benchmarks/dune` file and add the ignore rules to it.
=> Use dune data_only_dirs stanza instead of sed to ignore benchmarks

Makefile, run_config.json
05f9527357fddf25bc2a5bdebe87bdaed418a124 tried to fix a typo, but introduced another. This commit fixes problems with running mergesort benchmark
=> Fix typo in mergesort executable name

bench.Dockerfile
The Benchmarks section in the README documents this command to correctly run parallel benchmarks. We don't yet run it in Current bench, but this will make us future-proof.
=> Fix bench.Dockerfile to allow running chrt for parallel benchmarks

Makefile, run_all_custom.sh
This add pausetimes benchmarking on sequential programs in the nightly navajo and turing runs.
It also refactors `run_all_custom.sh` to be a bit more readable.
Tested locally on Navajo
=> Add pausetimes to nightly runs

.github/workflows/main.yml, bench.Dockerfile
`gnuplot` was added as a dependecy as a part of the PR #343 since a library for running the Irmin benchmarks depended on it. But, we don't currently run the `irmin` benchmarks and the `gnuplot` dependency installs a whole bunch of X11 dependencies when setting up the OS for running the benchmarks. This makes the setup longer than it needs to be, as of now.
=> Remove gnuplot dependency for benchmarks

Makefile, bench.Dockerfile
The CPU is specified using a build arg and currently the configuration is specific to work only for sequential benchmarks. The production worker currently has only 2 isolated CPUs and it is not yet clear how we are going to run the parallel benchmarks using Autumn.
=> Use correct CPU when running benchmarks using current-bench

run_all_custom.sh
The previous regex would parse a name like
`5.1.0+trunk+fabbing+prefetching_like_414` to `5.1.0+trunk\n414`.  This commit makes sure we only look at digits at the begnning of the config name.
*NOTE* The run_all_custom.sh script needs to be copied onto the bench machines.
=> Fix regex for getting CONFIG_VARIANT from CONFIG_NAME

multicore_parallel_navajo_run_config.json, multicore_parallel_run_config.json
When running the benchmarks via `opam exec -- dune build @${BUILD_BENCH_TARGET}` command, the additional `--` before the paramwrapper doesn't interact well with the pausetimes bash wrapper that evals an expression `eval "olly latency -o $TMP --json '$@'"`. Mysteriously, this eval fails with the error that `olly` executable couldn't be found when the additional `--` is present in the command. It is not entirely clear how this additional `--` affects the environment variables being set by opam exec, but this command removes them to get the benchmarks to run correctly.
=> Remove unnecessary double-dash in pausetimes command

Makefile
To keep track of the benchmarks that succeeded and failed, it would useful to have the RUN_CONFIG_JSON file with all the benchmark runs configuration. The results bench file can be compared against this to calculate the number of successful and failed benchmarks.
This PR is a complementary PR to https://github.com/ocaml-bench/sandmark-nightly/pull/117
=> Copy RUN_CONFIG_JSON file to results dir

Makefile, bench.Dockerfile
In my search to clean the Makefile, I discovered a bug:
We use `wget` to check for valid urls, but don't exit in case of failure. Adding the exits showcases that in some scenarios, `wget` might not be installed at all, which leads to printing "Error [URL] doesn't exist" even though it does exist, but the system didn't find wget.
The first commit of this PR fixes the printing and the exits, the second fixes the root bug and actually installs wget.
=> Fix wget usage in Makefile

README.md, multicore_parallel_navajo_run_config.json, multicore_parallel_run_config.json
Fix mpl benchmarks naming conventions and include it in the nightly runs. Additionally, document said conventions.
See https://github.com/ocaml-bench/sandmark/pull/404#issuecomment-1377033072
=> Include MPL benchmarks in the nightly pipeline

nightly_navajo.sh, nightly_turing.sh
The nightly cron jobs on Navajo have started to take almost a day, and sometimes this could lead to multiple benchmarks getting started at the same time. To prevent this we use the `flock` utility to detect if the process that previously owned a lock file is still alive, and not start another process if that's the case.
The call to `flock` is added to the nightly_* scripts so that it's more visible to the developers, rather than being hidden away in the crontab file.
=> Run the run_all_custom.sh script wrapped in flock

nightly_navajo.sh, nightly_turing.sh, run_all_custom.sh
- Prepend timestamps to messages in the logs
- Print the "KIND" when printing INFO message before starting benchmarks
**NOTE**: The nightly scripts on `turing` and `navajo` would need to be updated after this merge to deploy the changes.
*EDIT*: I've made sure the `ts` utility is available on both the machines.
=> Minor improvements to the cron job logs

.github/workflows/validate-multicore-config.yml, CONTRIBUTING.md, README.md, multicore_parallel_navajo_run_config.json, multicore_parallel_run_config.json, validate_multicore_config.py
This PR adds some basic tooling to validate benchmarks configurations added to `multicore_*_run_config.json` files.  We also add a CONTRIBUTING.md file that gives some basic instructions on adding a parallel benchmark. 
The PR also modifies the existing JSON files to fix validation errors. This validation removes the benchmarks listed in #446 from the nightly runs. The run_config.json files need to be triaged separately to see why some of the benchmarks are skipped from nightly runs (don't have the `macro_bench` tag), and need to be fixed.
=> Basic tooling to validate multicore_*_run_config.json

pausetimes/pausetimes
For other kinds of benchmark measurements, the IPython notebooks and the nightly UI Python code assumes that each line in the benchmark file is valid JSON.  For consistency, it would help the pausetimes data formatted similarly.
=> Print the JSON for each pausetimes benchmark in a single line

dependencies/template/ocaml-base-compiler/files/invoke-configure.sh
Previously, `OCAMLCONFIGOPTION` set to something like `"CC='gcc -Wa,-mbranches-within-32B' AS='as -mbranches-within-32B'"` would break the builds because of the spaces in the environment variables. The build failed with the following error:
configure: error: unrecognized option: `-Wa,-mbranches-within-32B''
For instance, see the build logs [here](https://github.com/ocaml-bench/sandmark-nightly/commit/1126df36c5d21bca87d95e1057d5fa3ef626b37b).
This commit ensures that spaces inside the single quoted strings are escaped correctly and the configure step runs correctly.
=> Ensure configure options with spaces in them don't break builds

benchmarks/markbench/dune, benchmarks/markbench/markbench.ml, run_config.json
This PR, a joint effort with @MisterDA, adds a very slightly modified version of @stedolan `markbench` micro-benchmark.
This micro-benchmark was first used in https://github.com/ocaml/ocaml/pull/10195 and then in https://github.com/ocaml/ocaml/pull/11827 to validate prefetching speedup while the GC is tracing blocks.
It could be useful as a sort of regression test running in Sandmark.
It would be preferable to use the reported seconds/GC time as calculated by the benchmark, which is reported on `stdout`, since it avoids accounting for setup time.
How could this could be achieved in Sandmark?
=> Add @stedolan `markbench` benchmark for prefetching

.github/workflows/main.yml, Makefile
They work with the latest versions of OCaml, and needn't be pinned to older versions or special branches/forks
=> Remove pins for sexplib0 and base libraries

.github/workflows/main.yml, Makefile, benchmarks/owl/dune, benchmarks/owl/owl_gc.ml, dependencies/template/dev-4.14.0.opam, dependencies/template/dev-5.x.opam, run_config.json
Originally taken from
https://gitlab.inria.fr/fangelet/ocaml-gc-regression-examples and supplied by Florian Angeletti (@Octachron). This code was supplied on [Performance regression with multiple domains between 5.0 and 5.1](https://github.com/ocaml-bench/sandmark/compare/main...tmcgilchrist:owl_gc_regression?expand=1#top). 
This test will output timings to stdout of the form `4.14.1 | 2.395s |  1949 |   487 ` representing   `compiler version, time, minor GC, major GC`. How will that output be captured by sandmark or is there instrumentation already to capture this sort of GC information?
=> Add Owl GC regression test case.

run_all_custom.sh
Closes ocaml/infrastructure#96
=> Allow .zip archive URLs along with .tar.gz

.github/workflows/main.yml, CONTRIBUTING.md, Makefile, README.md
I did a quick pass on the README and updated the documentation, based on questions and feedback from @tmcgilchrist.
=> Updates to the README and minor local workflow improvements

.github/workflows/main.yml, Makefile, run_all_custom.sh, run_all_parallel.sh, run_all_serial.sh
This reverts commits 19c98b1d8c7e3eba9b305cc318a139eab47faa66 and 7e5deb0063de2950fe56bec098cc0df08b433227. Upstream restored the variables that were removed in ocaml/ocaml#13201 in ocaml/ocaml#13244 for backward-compatibility.
=> Revert "Use pinned dune instead of system dune"

Makefile
This reverts commit e2fa97688e50f03790fc7e12814afe0471fd0081.
The ocaml/ocaml#13336 PR restored backward compatibility for the `Printtyp` module and the patch to `base` is no longer required.
=> Revert "Pin base to workaround Format_doc change"
