ocaml-bench/sandmark

Makefile
benchmarks/decompress/LICENSE
benchmarks/decompress/dune
benchmarks/decompress/test_decompress.ml
dependencies/packages/checkseum/checkseum.0.0.3/opam
dependencies/packages/decompress/decompress.0.8.1/opam
dependencies/packages/fmt/fmt.0.8.5/opam
dependencies/packages/optint/optint.0.0.2/opam
dependencies/packages/rresult/rresult.0.6.0/opam
dependencies/packages/uchar/uchar.0.0.2/opam

Simple test using the naive example in the decompress package that does a pure ocaml zlib compress/decompress.

Decompress test

---

benchmarks/multicore-structures/dune
benchmarks/multicore-structures/ms_queue.ml
benchmarks/multicore-structures/ms_queue.mli
benchmarks/multicore-structures/spsc_queue.ml
benchmarks/multicore-structures/spsc_queue.mli
benchmarks/multicore-structures/test_queue_parallel.ml
benchmarks/multicore-structures/test_queue_sequential.ml
benchmarks/multicore-structures/test_spsc_queue_parallel.ml
benchmarks/multicore-structures/test_spsc_queue_pingpong.ml
benchmarks/multicore-structures/test_spsc_queue_sequential.ml
benchmarks/multicore-structures/test_stack_parallel.ml
benchmarks/multicore-structures/test_stack_sequential.ml
benchmarks/multicore-structures/treiber_stack.ml
benchmarks/multicore-structures/treiber_stack.mli

Initial pass of some concurrent datastructures with tests for sequential and parallel. These should exercise different parts of the multicore runtime. Some are bottlenecked on promotion from the minor heap, others would benefit from inlining atomics.

Multicore structures

---

Makefile

so that the makefile will complete with an error rather than hang waiting for user input

Use --yes on opam switch 

---

.drone.yml
Makefile

coverage for parallelbench and multibench. Also this will give some multicore CI coverage through multibench.

Addition of parallelbench and multibench to the drone CI

---

Makefile

Give us a way to test and assert that the opam packages are all installed without error.

Add option to allow halt of run if an opam package install fails

---

Makefile
benchmarks/benchmarksgame/dune
benchmarks/benchmarksgame/fannkuchredux2.ml
benchmarks/benchmarksgame/revcomp2.ml

Addition of zarith dependency to get pidigits5 in benchmarksgame building

Add zarith dependency to get benchmarksgame/pidigits5 working

---

benchmarks/multicore-effects/algorithmic_differentiation.ml
benchmarks/multicore-effects/dune
benchmarks/multicore-effects/eratosthenes.ml
benchmarks/multicore-effects/ms_sched.ml
benchmarks/multicore-effects/ms_sched.mli
benchmarks/multicore-effects/queens.ml
benchmarks/multicore-effects/test_sched.ml

Some from https://github.com/kayceesrk/effects-examples with minor modifications and a simple parallel scheduler implementation.

Small number of tests that use effects

---

orun/orun.ml

Handle spaces and special characters that we might have in the command line arguments when outputting the command line to the JSON file.

More robust output of the command line in the JSON file

---

dependencies/packages/ocamlfind/ocamlfind.1.8.0/opam

Get ocamlfind working with 4.09 and later

Put in a custom pin to for ocamlfind 

---

benchmarks/simple-tests/lazy-dune.inc
benchmarks/simple-tests/lists-dune.inc
benchmarks/simple-tests/lists.ml
benchmarks/simple-tests/stacks.ml
benchmarks/simple-tests/stress.ml
benchmarks/simple-tests/weak-dune.inc
benchmarks/simple-tests/weakretain.ml
dependencies/repo

Quick pass to try and make the simple-tests more balanced in runtime (and parameters)

rebalance simple-tests

---

benchmarks/stdlib/string.inc
benchmarks/stdlib/string_bench.ml

Get some coverage of String compare, equal and split_on_char in the stdlib tests.

Addition of string_{compare,equal,split_on_char} to string stdlib tests

---

benchmarks/zarith/dune
benchmarks/zarith/zarith_fact.ml
benchmarks/zarith/zarith_fib.ml
benchmarks/zarith/zarith_pi.ml
benchmarks/zarith/zarith_tak.ml

add some Zarith specific benchmarks to sandmark

Initial import of some Zarith benchmarks

---

Makefile

from the makefile log the sandmark hash for this run

log the sandmark hash

---

README.md

This may add a bit of noise in README.md, if you think it's ok then feel free to merge it, otherwise I can move it or shorten it. :)

Add a note about running sandmark from non-standard locations

---

README.md

This PR tries to bring the README more up to date post #54. It also adds some info on the structure of sandmark along with how to configure existing and new benchmarks.

Update README.md to reflect PR #54

---

benchmarks/multicore-numerical/binary_trees_multicore.ml
benchmarks/multicore-numerical/dune
benchmarks/multicore-numerical/game_of_life_multicore.ml
benchmarks/multicore-numerical/matrix_multiplication_multicore.ml
benchmarks/multicore-numerical/matrix_multiplication_multicore_tilling.ml
benchmarks/multicore-numerical/nbody_multicore.ml
benchmarks/multicore-numerical/quicksort_multicore.ml
multicore_parallel_run_config.json

Added n body, quick sort, matrix multiplication.

More parallel benchmarks

---

Makefile

Issue: https://github.com/ocaml-bench/sandmark/issues/101
Initially, I thought of using the dune, and dune-project to generate the .opam file, but, the Makefile is actually current and maintained. Hence, I have updated the same to include dependency checks for both libgmp-dev and libdw-dev for Ubuntu.

Added depend target in Makefile

---

Makefile

Updated Makefile to include python and pip3 dependencies as mentioned in https://github.com/ocaml-bench/sandmark/issues/101.

Added python pip3 dependency

---

README.md

Updated README with JupyterHub information and reorganized the content a bit.

Refactored README and added JupyterHub info

---

README.md

Mention sudo access for run_all_parallel.sh script

---

.drone.yml
.gitignore
Makefile
benchmarks/multicore-numerical/dune

https://github.com/ocaml-bench/sandmark/issues/127

Add target to run parallel benchmarks in the CI

---

benchmarks/decompress/dune
benchmarks/decompress/test_decompress.ml
benchmarks/decompress/test_decompress_multicore.ml

A fix about mirage/decompress#86. I added some notes where, about compression, we can take the advantage of multicore - however I let you to see details about that.

Update decompress benchmarks

---

benchmarks/multicore-numerical/LU_decomposition_multicore.ml

This patch adds parallelisation to random numbers initialisation in LU decomposition benchmark. Performance comparison before and after the patch is below:
| Cores | Time before (s) | Speedup      | Time after (s) | Speedup     |
|-------|-----------------|--------------|----------------|-------------|
| 1     | 35.86           | 0.9428332404 | 33.81          | 1           |
| 2     | 18.31           | 1.84653195   | 17.13          | 1.973730298 |
| 4     | 9.48            | 3.566455696  | 8.74           | 3.868421053 |
| 8     | 5.1             | 6.629411765  | 4.64           | 7.286637931 |
| 12    | 3.9             | 8.669230769  | 3.5            | 9.66        |
| 16    | 3.11            | 10.87138264  | 2.74           | 12.33941606 |
| 20    | 2.68            | 12.61567164  | 2.32 …

LU decomposition: random numbers initialisation in parallel

---

benchmarks/multicore-minilight/parallel/camera.ml
benchmarks/multicore-numerical/LU_decomposition_multicore.ml
benchmarks/multicore-numerical/evolutionary_algorithm_multicore.ml

As a consequence of https://github.com/ocaml-multicore/ocaml-multicore/pull/404

change to new Domain.DLS API with initializer

---

.drone.yml

Just realised multicore pipeline was running the stock compiler, fixed in this PR.

fix compiler version in CI

---

README.md

This PR attempts to document the `environment` parameter that was introduced in #189 and make things clearer for people running experiments which use `OCAMLRUNPARAM` settings.
It is an update of #211 which didn't end up merging.

Attempt to improve the OCAMLRUNPARAM documentation

---

ocaml-versions/4.12.0+domains+effects.json
ocaml-versions/4.12.0+domains.json
ocaml-versions/4.12.0+stock.json

This PR adds ocaml-version files for:
- 4.12.0+stock
- 4.12.0+domains
- 4.12.0+domains+effects

Add configs for 4.12.0+stock, 4.12.0+domains, 4.12.0+domains+effects

---

benchmarks/multicore-numerical/mandelbrot6_multicore.ml

This PR improves the `mandlebrot6_multicore` scaling. It does this by:
- Using `parallel_for` in the work distribution
- Minor indent changes to make closer to the single domain version
Results from a (detuned) Zen2:
You could imagine going further than this by exploiting parallelism between the `output_bytes` and the work completion. However just using the `parallel_for` divide-and-conquer with default `chunk_sizes` is beating the existing code at 4 cores and more by a meaningful margin.

Better scaling for mandelbrot6_multicore

---

benchmarks/multicore-numerical/evolutionary_algorithm_multicore.ml

This PR makes some improvements to the ea benchmark.
Two changes:
- don't do the getting of the DLS state inside every `flip_coin` call, get it once
- insert a poll point into `fittest`; it turns out `Array.fold_left` is not inserting a poll point with `pop_fittest`
Zen2 results (detuned):

Better multicore ea benchmark

---

benchmarks/decompress/test_decompress_multicore.ml
benchmarks/multicore-minilight/parallel/minilight_multicore.ml
benchmarks/multicore-numerical/LU_decomposition_multicore.ml
benchmarks/multicore-numerical/binarytrees5_multicore.ml
benchmarks/multicore-numerical/evolutionary_algorithm_multicore.ml
benchmarks/multicore-numerical/floyd_warshall_multicore.ml
benchmarks/multicore-numerical/game_of_life_multicore.ml
benchmarks/multicore-numerical/mandelbrot6_multicore.ml
benchmarks/multicore-numerical/matrix_multiplication_multicore.ml
benchmarks/multicore-numerical/mergesort_multicore.ml
benchmarks/multicore-numerical/nbody_multicore.ml
benchmarks/multicore-numerical/quicksort_multicore.ml
benchmarks/multicore-numerical/spectralnorm2_multicore.ml
dependencies/packages/domainslib/domainslib.0.3.0/opam

To stay in-line with https://github.com/ocaml-multicore/domainslib/pull/31.

`num_domains` -> `num_additional_domains`

---

benchmarks/multicore-grammatrix/grammatrix_multicore.ml

The grammatrix benchmark does customised task distribution via channels. Replacing it with `parallel_for` didn't quite yield the same results. This patch adds some comments on the possible reasons with some observations from #239.

Add commentary on grammatrix

---

ocaml-versions/4.05.0.json
ocaml-versions/4.06.0.json
ocaml-versions/4.06.1+multicore+parallel.json
ocaml-versions/4.06.1+multicore+pausetimes+parallel.json
ocaml-versions/4.06.1+multicore+pausetimes.json
ocaml-versions/4.06.1+multicore+stw+parallel.json
ocaml-versions/4.06.1+multicore+stw+pausetimes+parallel.json
ocaml-versions/4.06.1+multicore+stw+pausetimes.json
ocaml-versions/4.06.1+multicore+stw.json
ocaml-versions/4.06.1+multicore.json
ocaml-versions/4.06.1+stock+instrumented.json
ocaml-versions/4.06.1+stock.json
ocaml-versions/4.06.1.json
ocaml-versions/4.07.0.json
ocaml-versions/4.07.1.json
ocaml-versions/4.08.0.json
ocaml-versions/4.10.0+multicore+parallel.json
ocaml-versions/4.10.0+multicore+pausetimes+parallel.json
ocaml-versions/4.10.0+multicore+pausetimes.json
ocaml-versions/4.10.0+multicore.json
ocaml-versions/4.10.0+rc2.json
ocaml-versions/4.10.0+stock+instrumented.json
ocaml-versions/4.10.0+stock.json
ocaml-versions/4.11.0+trunk+instrumented.json
ocaml-versions/README.md

Remove old variants

---

.drone.yml
Makefile
README.md
ocaml-versions/5.00.0+domains.json
run_config.json

The CI `Build Status` for the -main branch in the README should point to the -main branch.

Update README CI Build status to main branch

---

README.md

Updated README from the master branch.

Sync and update README from master branch

---

benchmarks/decompress/test_decompress_multicore.ml
benchmarks/multicore-minilight/parallel/camera.ml
benchmarks/multicore-numerical/LU_decomposition_multicore.ml
benchmarks/multicore-numerical/binarytrees5_multicore.ml
benchmarks/multicore-numerical/evolutionary_algorithm_multicore.ml
benchmarks/multicore-numerical/floyd_warshall_multicore.ml
benchmarks/multicore-numerical/game_of_life_multicore.ml
benchmarks/multicore-numerical/mandelbrot6_multicore.ml
benchmarks/multicore-numerical/matrix_multiplication_multicore.ml
benchmarks/multicore-numerical/nbody_multicore.ml
benchmarks/multicore-numerical/spectralnorm2_multicore.ml
dependencies/packages/domainslib/domainslib.0.4.1/opam

* Update to use `domainslib.0.4.1`.
* Wrap calls to `parallel_for` and `await` with Task `run`.

Use Task run in parallel benchmarks

---

run_all_custom.sh

In this PR:
* We always use a new pristine clone of Sandmark for each build.
* For every `sandmark-nightly-config` entry, we run both sequential and parallel benchmarks for `macro_bench`.
* For navajo server, the `multicore_parallel_navajo_run_config_filtered.json` is chosen. The default config JSON is `multicore_parallel_run_config_filtered.json`.

Use pristine sandmark clone for each build

---

README.md

Fix typo on line 173 of README

---

benchmarks/multicore-numerical/dune
benchmarks/multicore-numerical/nqueens.ml
benchmarks/multicore-numerical/nqueens_multicore.ml
multicore_parallel_navajo_run_config.json
multicore_parallel_run_config.json
run_config.json

This PR addresses #322. I was unsure what value to enter for the `board_size` parameter so I decided to go with `15` since it was the largest one mentioned in the comments of the `nqueens*.ml`. I also hope that the git workflow applied to update the previously outdated branch will be considered appropriate.

Add nqueens multicore to config

---

README.md

Added jo as dependency. See #346

---

benchmarks/multicore-numerical/mergesort.ml
benchmarks/multicore-numerical/mergesort_multicore.ml
multicore_parallel_navajo_run_config.json
multicore_parallel_run_config.json
run_config.json

Add new sequential and multicore versions of mergesort 

---

run_all_custom.sh

The `run_all_custom.sh` script has been updated to build perf-stat with the Sandmark nightly service. This is the backend update required for https://github.com/ocaml-bench/sandmark-nightly/pull/81.

Run perf stat with Sandmark nightly service

---

run_all_custom.sh

Closes ocaml-bench/sandmark-nightly#90

Detect COMMIT for archives of the form refs/pull

---

.github/workflows/main.yml
Makefile
dependencies/template/dev-5.2.0+trunk.opam
ocaml-versions/5.2.0+trunk.json

OCaml trunk version has been bumped up to 5.2 and this PR fixes broken sandmark builds.

Fix OCaml trunk builds

---

Makefile

This should https://github.com/ocaml-bench/sandmark-nightly-config/issues/22

Correctly use configure options specified in the sandmark-nightly-config JSON files

---

CODE_OF_CONDUCT.md

Adding contacts for Code of Conduct enforcement

Added missing Code of Conduct contact information
